source "https://rubygems.org"

gem "faraday", "~> 2.12"
gem "sinatra", "~> 4.0"
gem "puma", "~> 8.0"
gem "langchainrb", "~> 0.19.5"
gem "anthropic", "~> 1.32.0"
gem "rake", "~> 13.2"
gem "rack-cors", "~> 3.0"
gem "omniauth", "~> 2.1"
gem "omniauth-auth0", "~> 3.1"

group :development do
  gem "rubocop", "~> 1.86", require: false
  gem "rubocop-performance", "~> 1.24", require: false
end

group :test do
  gem "minitest", "~> 6.0"
  gem "minitest-mock", "~> 5.27"
  gem "rack-test", "~> 2.2"
end
