require "rake/testtask"

desc "Run backend tests"
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "src"
  t.pattern = "test/**/*_test.rb"
  t.verbose = true
end

desc "Run rubocop"
task :lint do
  sh "bundle exec rubocop"
end

desc "Run lint and tests"
task default: [:lint, :test]
